import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import { ThemeProvider } from "./providers";

// Define local font
const myFont = localFont({
  src: "/fonts/expressway.otf", // Path to your OTF font file
  display: "swap",
  variable: "--font-body",
});

const logoFont = localFont({
  src: "/fonts/BebasNeue-Regular.otf", // Path to your OTF font file
  display: "swap",
  variable: "--font-logo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  suppressHydrationWarning={true}>
      <body className={`${myFont.variable} ${logoFont.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
